#!/usr/bin/env python3
"""Build filmdesk/index.html — the front door — from tips.md and projects/index.json.
    python3 filmdesk/desk.py
"""
import json, re, html, pathlib
D = pathlib.Path(__file__).resolve().parent; esc = lambda t: html.escape(str(t), quote=True)
tips = (D / "tips.md").read_text(); ix = json.load(open(D / "projects" / "index.json")) if (D / "projects" / "index.json").exists() else []
def inline(t):  # **bold**, `code`, *em*
    t = esc(t); t = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", t); t = re.sub(r"`(.+?)`", r"<code>\1</code>", t); return re.sub(r"(?<!\*)\*(?!\*)(.+?)\*", r"<em>\1</em>", t)
groups, cur = [], None
for line in tips.splitlines():
    if line.startswith("## "): cur = {"h": line[3:].strip(), "items": []}; groups.append(cur)
    elif re.match(r"^\d+\. ", line) and cur: n, body = line.split(". ", 1); cur["items"].append((n, body))
tips_html = "".join(f'<div class="tg"><h3>{esc(g["h"])}</h3><ol start="{g["items"][0][0] if g["items"] else 1}">' + "".join(f"<li>{inline(b)}</li>" for _, b in g["items"]) + "</ol></div>" for g in groups)
cards = "".join(f'''<a class="doc primary" href="projects/{esc(r["slug"])}/board.html"><span class="k">{esc(r["kind"])} · {esc(r["aspect"])}</span><h3>{esc(r["title"])}</h3><p>{esc(r["logline"])}</p>
<div class="stats"><span><b>{r["shots"]}</b> shots</span><span><b>{r["takes"]}</b> takes</span><span><b>{r["picks"]}</b> picks</span><span><b>{r["scored"]}</b> scored</span><span><b>{r["unshot"]}</b> unshot</span><span><b>{esc(r["runtime"])}</b> runtime</span></div>
<span class="f"><span>{esc(r["byline"])}</span><span>built {esc(r["built"])}</span></span></a>''' for r in ix) or '<p class="muted">No projects yet — the first build.py run adds one here.</p>'
page = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>filmdesk</title><meta name="description" content="One folder per film: every generation a film uses, pulled from a single Higgsfield project and laid out as a shot board with picks, alternates, prompts, scores and a ledger.">
<style>
:root{{--ground:#EDEFF5;--surface:#FFFFFF;--surface-2:#E3E6EF;--line:#BFC6D8;--line-soft:#DCE1EC;--ink:#0E1017;--ink-2:#3D4459;--ink-3:#646B80;--gold:#8A5A00;--gold-soft:#FBEBC4;--gold-line:#D9AC46;--void:#3A32DC;--void-soft:#DEDCFF;--void-line:#9A96F5;--coral:#BC3317;--coral-soft:#FFDCD1;--coral-line:#EE9273;--jade:#046B45;--jade-soft:#CDF0E0;--jade-line:#5EBE95;--shadow:0 1px 2px rgba(16,18,28,.06),0 8px 24px -12px rgba(16,18,28,.18);
--display:"Iowan Old Style","Palatino Linotype",Palatino,"Book Antiqua",Georgia,serif;--body:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;--mono:ui-monospace,"SF Mono","Cascadia Code","JetBrains Mono",Menlo,Consolas,monospace}}
@media (prefers-color-scheme:dark){{:root:not([data-theme="light"]){{--ground:#07080D;--surface:#111319;--surface-2:#1A1D28;--line:#333A4D;--line-soft:#20242F;--ink:#F4F0E6;--ink-2:#A8AEC2;--ink-3:#767D92;--gold:#FFBE4A;--gold-soft:#33260F;--gold-line:#6B4E18;--void:#9B9DFF;--void-soft:#1C1D3D;--void-line:#403FA0;--coral:#FF8F6B;--coral-soft:#3A1C13;--coral-line:#7A3826;--jade:#4FDCA0;--jade-soft:#0A2E20;--jade-line:#1D6B4C;--shadow:0 1px 2px rgba(0,0,0,.4),0 12px 32px -14px rgba(0,0,0,.7)}}}}
:root[data-theme="dark"]{{--ground:#07080D;--surface:#111319;--surface-2:#1A1D28;--line:#333A4D;--line-soft:#20242F;--ink:#F4F0E6;--ink-2:#A8AEC2;--ink-3:#767D92;--gold:#FFBE4A;--gold-soft:#33260F;--gold-line:#6B4E18;--void:#9B9DFF;--void-soft:#1C1D3D;--void-line:#403FA0;--coral:#FF8F6B;--coral-soft:#3A1C13;--coral-line:#7A3826;--jade:#4FDCA0;--jade-soft:#0A2E20;--jade-line:#1D6B4C;--shadow:0 1px 2px rgba(0,0,0,.4),0 12px 32px -14px rgba(0,0,0,.7)}}
*{{box-sizing:border-box}} html{{scroll-behavior:smooth;scroll-padding-top:70px}} body{{margin:0;background:var(--ground);color:var(--ink);font:16px/1.6 var(--body);padding:0 0 90px;overflow-x:hidden}} a{{color:inherit}}
.wrap{{max-width:1080px;margin:0 auto;padding:0 clamp(16px,3vw,26px)}}
header.top{{border-bottom:1px solid var(--line);background:linear-gradient(180deg,var(--surface),var(--ground));padding:44px 0 34px}}
.eyebrow{{font:600 10.5px/1 var(--mono);letter-spacing:.19em;text-transform:uppercase;color:var(--ink-3);display:block;margin-bottom:14px}}
h1{{font:400 clamp(34px,6vw,54px)/1.04 var(--display);margin:0 0 14px;letter-spacing:-.01em}} .lede{{margin:0;max-width:64ch;color:var(--ink-2);font-size:17px}}
.badges{{display:flex;flex-wrap:wrap;gap:8px;margin-top:22px}} .badge{{font:600 10px/1 var(--mono);letter-spacing:.11em;text-transform:uppercase;padding:6px 9px;border-radius:5px;border:1px solid var(--line);background:var(--surface-2);color:var(--ink-2)}} .badge.on{{background:var(--jade-soft);color:var(--jade);border-color:var(--jade-line)}}
nav.jump{{position:sticky;top:0;z-index:8;background:color-mix(in srgb,var(--ground) 92%,transparent);backdrop-filter:blur(9px);border-bottom:1px solid var(--line);margin-bottom:38px}}
nav.jump .wrap{{display:flex;gap:2px;overflow-x:auto;scrollbar-width:none}} nav.jump a{{font:600 10.5px/1 var(--mono);letter-spacing:.13em;text-transform:uppercase;color:var(--ink-3);text-decoration:none;padding:15px 13px;border-bottom:2px solid transparent;white-space:nowrap}} nav.jump a:hover{{color:var(--ink);border-bottom-color:var(--gold-line)}}
section{{margin-bottom:52px;scroll-margin-top:74px}} h2{{font:400 27px/1.2 var(--display);margin:0 0 8px}} h2 .n{{font:600 11px/1 var(--mono);letter-spacing:.16em;color:var(--ink-3);vertical-align:middle;margin-right:12px}} .sec-head{{margin-bottom:20px}} .sec-head p{{margin:0;color:var(--ink-2);max-width:72ch;font-size:15px}}
.docs{{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}} a.doc,.doc{{display:flex;flex-direction:column;gap:10px;text-decoration:none;background:var(--surface);border:1px solid var(--line);border-radius:11px;padding:22px 22px 20px;box-shadow:var(--shadow)}} a.doc:hover{{border-color:var(--gold-line)}} a.doc:focus-visible{{outline:2px solid var(--void);outline-offset:3px}}
.doc .k{{font:600 9.5px/1 var(--mono);letter-spacing:.15em;text-transform:uppercase;color:var(--gold)}} .doc h3{{font:600 19px/1.25 var(--body);margin:0}} .doc p{{margin:0;font-size:14px;color:var(--ink-2);flex:1}} .doc .f{{font:11px/1 var(--mono);color:var(--ink-3);border-top:1px solid var(--line-soft);padding-top:11px;display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}} a.doc.primary{{border-color:var(--gold-line);background:linear-gradient(180deg,var(--gold-soft),var(--surface) 62%)}}
.stats{{display:flex;flex-wrap:wrap;gap:6px 14px;font:12px var(--mono);color:var(--ink-3)}} .stats b{{color:var(--ink);font-weight:600}}
.steps{{display:flex;flex-direction:column;border-top:1px solid var(--line)}} .step{{display:grid;grid-template-columns:52px 1fr;gap:16px;padding:17px 0;border-bottom:1px solid var(--line-soft)}} .step .sn{{font:600 12px/1.5 var(--mono);color:var(--ink-3);letter-spacing:.08em}} .step h4{{margin:0 0 5px;font:600 15.5px/1.35 var(--body)}} .step p{{margin:0;font-size:14px;color:var(--ink-2)}} .step p+p{{margin-top:5px}}
code{{font:12.5px/1.45 var(--mono);background:var(--surface-2);border:1px solid var(--line-soft);border-radius:4px;padding:1.5px 5px;word-break:break-word}} pre{{font:12.5px/1.6 var(--mono);background:var(--surface-2);border:1px solid var(--line);border-radius:8px;padding:12px 14px;overflow-x:auto;margin:8px 0 0}}
.panel{{background:var(--surface);border:1px solid var(--line);border-radius:11px;padding:24px;box-shadow:var(--shadow);margin-bottom:18px}} .panel>h3{{margin:0 0 6px;font:600 16px/1.3 var(--body)}} .panel p{{margin:0 0 10px;font-size:14.5px;color:var(--ink-2)}} .panel p:last-child{{margin:0}}
.loop{{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}} .lp{{background:var(--surface);border:1px solid var(--line);border-radius:9px;padding:14px 15px}} .lp b{{display:block;font:600 10px/1 var(--mono);letter-spacing:.14em;text-transform:uppercase;color:var(--gold);margin-bottom:8px}} .lp h4{{margin:0 0 5px;font:600 15px/1.3 var(--body)}} .lp p{{margin:0;font-size:13px;color:var(--ink-2)}} .lp code{{display:block;margin-top:8px;white-space:pre-wrap}}
.tips{{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px}} .tg{{background:var(--surface);border:1px solid var(--line);border-radius:11px;padding:18px 20px 14px}} .tg h3{{margin:0 0 8px;font:600 15px/1.3 var(--body)}} .tg ol{{margin:0;padding-left:22px;font-size:14px;color:var(--ink-2)}} .tg li{{margin:6px 0}} .tg li b{{color:var(--ink)}}
.muted{{color:var(--ink-3)}} footer{{color:var(--ink-3);font-size:13px;margin-top:40px}}
@media (prefers-reduced-motion:reduce){{*{{transition:none!important}}}}
</style></head><body>
<header class="top"><div class="wrap"><span class="eyebrow">filmdesk · a folder per film</span><h1>One project. Every take. The cut, take by take.</h1>
<p class="lede">Every generation a film uses, pulled from <b>one Higgsfield project</b> and laid out as a shot board — a pick per shot, the alternates beside it, each tile a real render by URL — with prompts for what is not shot, Predictor scores for what is, and a ledger of everything the desk made.</p>
<div class="badges"><span class="badge on">{len(ix)} project{"s" if len(ix)!=1 else ""}</span><span class="badge">ingest · build · generate</span><span class="badge">bring your own keys</span><span class="badge">regenerate, don't hand-edit</span></div></div></header>
<nav class="jump"><div class="wrap"><a href="#what">What it is</a><a href="#projects">Projects</a><a href="#start">Start a project</a><a href="#loop">The loop</a><a href="#rule">One folder</a><a href="keys.html">Keys</a><a href="#tips">Tips</a></div></nav>
<main class="wrap">
<section id="what"><div class="sec-head"><h2><span class="n">01</span>Three things</h2></div><div class="docs">
<div class="doc"><span class="k">the board</span><h3>The cut, take by take</h3><p>Shots in running order. One pick each, up to three alternates, every tile a render by URL with its prompt, references, chaining and score. Unshot shots carry their paste-ready prompt.</p></div>
<div class="doc"><span class="k">the ledger</span><h3>What this project made</h3><p>Every submission the desk sends is on <code>project.json</code> before anyone waits for it. Ingest admits anything on the ledger regardless of what the API can filter on.</p></div>
<div class="doc"><span class="k">the keys</span><h3>Yours, local, never committed</h3><p>A page that holds your keys in this browser only and exports a gitignored <code>keys.env</code>, with a link to get each one.</p></div></div></section>
<section id="projects"><div class="sec-head"><h2><span class="n">02</span>Projects</h2><p>One card per <code>projects/&lt;slug&gt;/</code>. <code>build.py</code> keeps this list current.</p></div><div class="docs">{cards}</div></section>
<section id="start"><div class="sec-head"><h2><span class="n">03</span>Start a project</h2></div><div class="steps">
<div class="step"><span class="sn">01</span><div><h4>Copy the example</h4><p><code>cp filmdesk/project.example.json filmdesk/projects/&lt;slug&gt;/project.json</code></p><p>Title, kind, format, the Higgsfield project URL and folder id, the date window.</p></div></div>
<div class="step"><span class="sn">02</span><div><h4>Write the cast as ids</h4><p>Characters, environments, props, effects — <code>name → element uuid</code>. This list is what makes a generation yours. Souls one per name.</p></div></div>
<div class="step"><span class="sn">03</span><div><h4>Write the shots</h4><p>Id, act, title, duration, audio on or off, and the prompt with <code>@[name](uuid)</code> references. Leave <code>pick</code> empty; the board chooses by score until you decide.</p></div></div>
<div class="step"><span class="sn">04</span><div><h4>Ingest the history</h4><p><code>python3 filmdesk/ingest.py filmdesk/projects/&lt;slug&gt; &lt;dump&gt; [...]</code></p><p>Dumps are the files the Higgsfield connector writes when history is paged in Claude. Anything not made with your cast is dropped and counted.</p></div></div>
<div class="step"><span class="sn">05</span><div><h4>Build and open</h4><p><code>python3 filmdesk/build.py filmdesk/projects/&lt;slug&gt;</code> then <code>filmdesk/serve.command</code>. Clips play inline when served or opened locally.</p></div></div>
<div class="step"><span class="sn">06</span><div><h4>Keys, then generate</h4><p>Export <code>keys.env</code> from the <a href="keys.html">keys page</a>. <code>python3 filmdesk/generate.py filmdesk/projects/&lt;slug&gt; --shot S5 --model &lt;cloud model id&gt; --prompt-from-shot</code>. The request id lands on the ledger on acceptance.</p></div></div></div></section>
<section id="loop"><div class="sec-head"><h2><span class="n">04</span>The loop</h2><p>Six steps, round and round, until the picks are the film.</p></div><div class="loop">
<div class="lp"><b>1 · ingest</b><h4>Admit this project's takes</h4><p>By cast, by ledger, by hand map. Newest first.</p><code>ingest.py &lt;slug&gt; dump…</code></div>
<div class="lp"><b>2 · score</b><h4>Run the Predictor</h4><p>Every take ≤16s, two at a time. Save as <code>scores.json</code>.</p><code>ingest.py … --scores scores.json</code></div>
<div class="lp"><b>3 · build</b><h4>Lay the board</h4><p>Pick by your call, else by score, else newest.</p><code>build.py &lt;slug&gt;</code></div>
<div class="lp"><b>4 · choose</b><h4>Look, then decide</h4><p>Write <code>pick</code> and <code>alternates</code> into the shot. Note why.</p><code>project.json → shots[]</code></div>
<div class="lp"><b>5 · generate</b><h4>Make what is missing</h4><p>From the shot's prompt, onto the ledger.</p><code>generate.py … --prompt-from-shot</code></div>
<div class="lp"><b>6 · deliver</b><h4>Pull the picks</h4><p>Cut order, native size ×2 at most, titles in the NLE.</p><code>board.html → open the clip</code></div></div></section>
<section id="rule"><div class="sec-head"><h2><span class="n">05</span>One folder, and what that can mean</h2></div><div class="panel">
<p><b>The desk is exclusive to one Higgsfield project.</b> It enforces that the only way the API allows: <b>admission by cast</b> (a take is yours if it was made with an element in your cast), <b>ledger on submission</b> (the desk records what it makes before it waits), and <b>a hand map</b> for anything you place yourself.</p>
<p><b>Folder placement itself stays in the web app.</b> No image model and almost no video model accepts a folder id over the API. When a rule needs the generation history to live inside the project, generate there in Cinema Studio; the desk will find those renders by their cast and lay them out.</p>
<p class="muted">History pulls come through the Higgsfield connector in Claude, which pages the account and writes files. Point <code>ingest.py</code> at them.</p></div></section>
<section id="tips"><div class="sec-head"><h2><span class="n">06</span>Working tips</h2><p>What one production learned, in the order you meet it. Source: <code>tips.md</code>.</p></div><div class="tips">{tips_html}</div></section>
<footer>Built by <code>filmdesk/desk.py</code> from <code>tips.md</code> and <code>projects/index.json</code>. Regenerate, don't hand-edit.</footer></main></body></html>'''
(D / "index.html").write_text(page); print("wrote filmdesk/index.html", len(page), "bytes ·", len(ix), "project cards ·", len(groups), "tip groups")
